#!/bin/bash
# Generator for all 38 Indonesian provinces
# Creates landing pages for each unit business

echo "🚀 Generating Landing Pages for 38 Provinces..."
echo "=============================================="

# 38 Provinces of Indonesia
PROVINCES=(
    "Aceh"
    "Sumatera Utara"
    "Sumatera Barat"
    "Riau"
    "Jambi"
    "Sumatera Selatan"
    "Bengkulu"
    "Lampung"
    "DKI Jakarta"
    "Jawa Barat"
    "Jawa Tengah"
    "DI Yogyakarta"
    "Jawa Timur"
    "Banten"
    "Bali"
    "Nusa Tenggara Barat"
    "Nusa Tenggara Timur"
    "Kalimantan Barat"
    "Kalimantan Tengah"
    "Kalimantan Selatan"
    "Kalimantan Timur"
    "Kalimantan Utara"
    "Sulawesi Utara"
    "Sulawesi Tengah"
    "Sulawesi Selatan"
    "Sulawesi Tenggara"
    "Gorontalo"
    "Sulawesi Barat"
    "Maluku"
    "Maluku Utara"
    "Papua"
    "Papua Barat"
    "Papua Tengah"
    "Papua Pegunungan"
    "Papua Barat Daya"
)

PROVINCE_CODES=(
    "aceh"
    "sumut"
    "sumbar"
    "riau"
    "jambi"
    "sumsel"
    "bengkulu"
    "lampung"
    "jakarta"
    "jabar"
    "jateng"
    "yogyakarta"
    "jatim"
    "banten"
    "bali"
    "ntb"
    "ntt"
    "kalbar"
    "kalteng"
    "kalsel"
    "kaltim"
    "kalut"
    "sulut"
    "sulteng"
    "sulsel"
    "sulteng"
    "gorontalo"
    "sulbar"
    "maluku"
    "malut"
    "papua"
    "papbar"
    "papteng"
    "pappg"
    "papbar Daya"
)

# Unit businesses
UNITS=(
    "digimart"
    "linkshort"
    "airdrop"
    "microtask"
    "survey"
)

UNIT_NAMES=(
    "DigiMart"
    "LinkShort Pro"
    "AirdropHunter"
    "MicroTask Pro"
    "SurveyPro"
)

UNIT_DESCRIPTIONS=(
    "Toko Produk Digital | Voucher Game, Token Listrik, Pulsa"
    "Shorten Links & Earn Money | Monetisasi Link Anda"
    "Find & Claim Crypto Airdrops | Hunter Airdrop Terbaik"
    "Earn Money Doing Micro Tasks | Tugas Kecil Penghasilan Besar"
    "Create & Earn from Surveys | Survei Berbayar"
)

echo "Provinces: ${#PROVINCES[@]}"
echo "Units: ${#UNITS[@]}"
echo ""
echo "Files will be generated in:"
echo "/workspace/project/MAHA-LAKSHMI-CORP/indonesia-province/"
echo ""
echo "Structure:"
echo "- digimart/ (${#PROVINCES[@]} folders)"
echo "- linkshort/ (${#PROVINCES[@]} folders)"
echo "- airdrop/ (${#PROVINCES[@]} folders)"
echo "- microtask/ (${#PROVINCES[@]} folders)"
echo "- survey/ (${#PROVINCES[@]} folders)"
echo ""
echo "✅ Generator script ready!"
echo ""
echo "To generate files, run: php generate-province.php"
