#!/usr/bin/env python3
"""
Global Sales Invoice Generator
MAHA LAKSHMI HOLDINGS
Generates USDT invoices for clients
"""

import json
from datetime import datetime
from pathlib import Path

USDT_WALLET = "TNFs1SP2C8HxGSJkSH3hJamf8ukgtnW7U6"

def generate_invoice(client_name, client_email, service, amount_usdt, invoice_number=None):
    """Generate USDT invoice"""
    
    if invoice_number is None:
        today = datetime.now().strftime("%Y%m%d")
        invoice_number = f"INV-GLOBAL-{today}-{len([f for f in Path('invoices').glob('*.md')]) + 1:03d}"
    
    invoice_content = f"""# 📄 INVOICE

**Invoice Number:** {invoice_number}
**Date:** {datetime.now().strftime("%Y-%m-%d")}
**Due Date:** {datetime.now().strftime("%Y-%m-%d")}

---

## FROM

**Company:** MAHA LAKSHMI HOLDINGS
**Email:** alex@mahalakshmi.io
**Website:** www.mahalakshmi.io

---

## TO

**Name:** {client_name}
**Email:** {client_email}

---

## SERVICES

| Item | Description | Amount (USDT) |
|------|-------------|---------------|
| 1 | {service} | ${amount_usdt:.2f} |
| | | |
| **TOTAL** | | **${amount_usdt:.2f}** |

---

## 💳 PAYMENT

**Currency:** USDT (TRC20)
**Amount:** ${amount_usdt:.2f}

**USDT Wallet Address:**
```
{USDT_WALLET}
```

**Payment Instructions:**
1. Send exact USDT amount to the wallet address above
2. Use TRC20 network only
3. Send confirmation to: alex@mahalakshmi.io

---

## 📋 NOTES

- This invoice is valid for 7 days
- Payment confirms agreement to terms
- Project begins after payment confirmation
- 50% deposit required for projects over $1000

---

*Generated by MAHA LAKSHMI HOLDINGS AI Agent*
*Date: {datetime.now().isoformat()}*
"""
    
    # Save invoice
    Path("invoices").mkdir(exist_ok=True)
    invoice_path = f"invoices/{invoice_number}.md"
    with open(invoice_path, 'w') as f:
        f.write(invoice_content)
    
    # Update deals pipeline
    try:
        with open('deals-pipeline.json', 'r') as f:
            deals = json.load(f)
    except:
        deals = {"deals": [], "stats": {"total_deals": 0, "total_value": 0}}
    
    deals["deals"].append({
        "id": invoice_number,
        "client_name": client_name,
        "client_email": client_email,
        "service": service,
        "amount": amount_usdt,
        "status": "invoice_sent",
        "created_at": datetime.now().isoformat()
    })
    deals["stats"]["total_deals"] = len(deals["deals"])
    
    with open('deals-pipeline.json', 'w') as f:
        json.dump(deals, f, indent=2)
    
    print(f"✅ Invoice generated: {invoice_path}")
    print(f"💰 Amount: ${amount_usdt} USDT")
    print(f"📧 Sent to: {client_email}")
    
    return invoice_number

def main():
    print("🚀 MAHA LAKSHMI HOLDINGS - Invoice Generator")
    print("=" * 50)
    print(f"\n💳 USDT Wallet: {USDT_WALLET}")
    print("\nUsage:")
    print("  generate_invoice('Client Name', 'email@example.com', 'Service Description', 500)")
    print("\nExample:")
    print("  generate_invoice('John Smith', 'john@company.com', 'Website Development', 800)")

if __name__ == "__main__":
    main()
