services:
  - type: web
    name: maha-lakshmi-corp
    env: docker
    region: singapore
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
