#!/usr/bin/env python3
"""
GAURANGA - Email Report Sender
Send daily report to CEO (Pak Pur)
Email: gaurangga168@gmail.com
"""

import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# Configuration
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "gaurangga168@gmail.com"
# PASTE YOUR APP PASSWORD HERE
APP_PASSWORD = "YOUR_APP_PASSWORD_HERE"
RECIPIENT_EMAIL = "gaurangga168@gmail.com"

def send_daily_report():
    """Send daily report to CEO via email"""
    
    # Email content
    today = datetime.now().strftime("%Y-%m-%d %H:%M WIB")
    
    subject = f"📊 GAURANGA Daily Report - {today}"
    
    body = f"""
<html>
<body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 20px; text-align: center;">
        <h1 style="color: white; margin: 0;">📊 GAURANGA DAILY REPORT</h1>
        <p style="color: white;">Daily Update untuk Pak Pur</p>
    </div>
    
    <div style="padding: 20px;">
        <h2 style="color: #333;">👋 Selamat Pagi, Pak Pur!</h2>
        <p style="color: #666;">Laporan harian untuk <strong>{today}</strong></p>
        
        <div style="background: #f5f5f5; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin-top: 0;">📈 STATUS KORPORAT</h3>
            <table style="width: 100%; border-collapse: collapse;">
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd;"><strong>💰 Revenue</strong></td>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right;">Rp 0</td>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right; color: red;">🔴</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd;"><strong>🏢 Companies</strong></td>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right;">10</td>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right; color: green;">✅</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd;"><strong>🤖 Agents</strong></td>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right;">6/60</td>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right;">⚠️</td>
                </tr>
                <tr>
                    <td style="padding: 8px;"><strong>📋 Leads</strong></td>
                    <td style="padding: 8px; text-align: right;">0</td>
                    <td style="padding: 8px; text-align: right; color: red;">🔴</td>
                </tr>
            </table>
        </div>
        
        <div style="background: #e8f5e9; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin-top: 0;">🏆 PRIORITY HARI INI</h3>
            <ol style="margin: 0; padding-left: 20px;">
                <li>Deploy Bali Travel landing page</li>
                <li>Setup GitHub repos</li>
                <li>Mulai lead generation</li>
            </ol>
        </div>
        
        <div style="background: #fff3e0; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin-top: 0;">💰 TARGET REVENUE</h3>
            <p>Bulan 1: <strong>Rp 10.000.000</strong></p>
            <p>Bulan 3: <strong>Rp 60.000.000</strong></p>
            <p>Bulan 6: <strong>Rp 100.000.000</strong></p>
        </div>
        
        <div style="background: #e3f2fd; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin-top: 0;">🏦 INFO BANK</h3>
            <p><strong>BCA: 6485086645</strong></p>
            <p>a/n: i Made Purna Ananda</p>
        </div>
        
        <p style="color: #888; font-size: 12px; margin-top: 30px;">
            <em>Motto: "Setiap kesalahan harus ada solusinya!"</em><br>
            Generated by GAURANGA AI Agent • {today}
        </p>
    </div>
</body>
</html>
"""
    
    try:
        # Create message
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = SENDER_EMAIL
        msg['To'] = RECIPIENT_EMAIL
        
        # Attach HTML body
        html_part = MIMEText(body, 'html')
        msg.attach(html_part)
        
        # Connect to server and send
        print(f"Connecting to {SMTP_SERVER}:{SMTP_PORT}...")
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        print("Logging in...")
        server.login(SENDER_EMAIL, APP_PASSWORD)
        print(f"Sending email to {RECIPIENT_EMAIL}...")
        server.sendmail(SENDER_EMAIL, RECIPIENT_EMAIL, msg.as_string())
        server.quit()
        
        print("✅ Email sent successfully!")
        return True
        
    except Exception as e:
        print(f"❌ Error: {e}")
        return False

def send_simple_alert(subject, message):
    """Send simple alert/notification"""
    try:
        msg = MIMEMultipart()
        msg['Subject'] = f"🔔 {subject}"
        msg['From'] = SENDER_EMAIL
        msg['To'] = RECIPIENT_EMAIL
        
        body = f"""
        <html>
        <body>
            <h2>🔔 {subject}</h2>
            <p>{message}</p>
            <hr>
            <p><em>GAURANGA AI • {datetime.now().strftime('%Y-%m-%d %H:%M')}</em></p>
        </body>
        </html>
        """
        
        html_part = MIMEText(body, 'html')
        msg.attach(html_part)
        
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SENDER_EMAIL, APP_PASSWORD)
        server.sendmail(SENDER_EMAIL, RECIPIENT_EMAIL, msg.as_string())
        server.quit()
        
        return True
    except Exception as e:
        print(f"❌ Error: {e}")
        return False

if __name__ == "__main__":
    print("📧 GAURANGA Email Report Sender")
    print("=" * 40)
    
    # Test send
    send_daily_report()
